name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.6.0
homepage: https://github.com/mwaylabs/flutter-apns

publish_to: 'none'

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_apns_only:
    git:
      url: https://github.com/pfraunlob/flutter-apns
      path: flutter_apns_only/

dev_dependencies:
  flutter_test:
    sdk: flutter
